version: '3.9'
services:
  frontend:
    env_file: 
      - ../apps/frontend/environments/.docker.env
    profiles:
      - frontend
      - all
    build:
      context: ../
      dockerfile: apps/frontend/Dockerfile
    container_name: frontend
    volumes:
      - frontend-volume:/usr/src/app
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
  backend:
    env_file: 
      - ../apps/backend/environments/.docker.env
    profiles:
      - backend
      - all
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    volumes:
      - backend-volume:/usr/src/app
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  database:
    image: mysql:latest
    container_name: database
    volumes:
      - database-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
    ports:
      - ${MYSQL_PORT}:3306
volumes:
  frontend-volume:
  backend-volume:
  database-volume:
name: akkor_hotel