name: CI
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'pnpm'

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306 
          character set server: 'utf8' 
          mysql database: 'akkor_hotel' 
          mysql root password: 'root'


      - run: pnpm install
      - run: pnpm exec nx affected --target=build --parallel --max-parallel=3
      - run: pnpm exec nx affected --target=lint --parallel --max-parallel=2

      - name: Set up Docker Compose
        uses: docker/compose@v2.2.3
        with:
          compose-version: 1.29.2

      - name: Build and run containers
        run: docker-compose -f test/docker-compose-ci.yml up -d

      - run: pnpm exec nx affected --target=test --run-in-band