name: CI
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  main:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'pnpm'


      - run: pnpm install
      - run: pnpm exec nx run-many --target=build --all
      - run: pnpm exec nx run-many --target=lint --all

      - name: Build and run containers
        run: docker-compose -f test/docker-compose-ci.yml up -d

      - run: pnpm exec nx run-many --target=test backend --run-in-band
